apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: development.familytree365.com
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: 80
